### PR TITLE
Experimental Feature: /etc/scratchpkg.world

### PR DESCRIPTION
**Pull request by XDream8**

### CODE REVIEW

**Comment by XDream8** [comment]
My vim is configured to remove all trailing spaces. that is why there is so many additions and removes

**Comment by XDream8** [comment]
I think this is ready but more testing is needed

**Comment by emmett1** [comment]
Ok from what saw in your commit;
1. reinstall a package adding it to world
2. install using no-dep option adding it to world
3. running 'scratch install pkg' adding it to world, but after everything is installed.
4. world file is in /etc/scratchpkg.world

My comment for those;
1. I dont think reinstall a package should add to world. What if that package is a dependency for others parents packages?
2. This is ok.
3. This is not good, what if installing a bunch of package in one single install command then build error happen in the middle of all packages? Nothing will added to world.
4. I've been thinking to place world file in /var/lib/scratchpkg along with other non-hand-editable directory like package database. But still need opinion, should just place it in /etc then user can edit it by hand manually. Or add 'add to world' option into scratch.

**Comment by emmett1** [comment]
This new commit you made is, add all parent pkg into world after first dependency is installed.

**Comment by emmett1** [comment]
I think what you need to do is, after each dependency is installed, check whether its a parent pkg. if its parent pkg, add to world.

**Comment by XDream8** [comment]
> I think what you need to do is, after each dependency is installed, check whether its a parent pkg. if its parent pkg, add to world.

Like this, we already add parent pkgs to world after their dependencies are installed.

INST variable uses ``scratch_deplist`` which it prints ports dependencies and lastly includes the parent port

IPKG variable contains the parent ports we wanted to install

So for example if $ii from $IPKG equals to $int from $INST

This is from my debugging
```
ii=telegram-desktop-bin
int=telegram-desktop-bin
Adding telegram-desktop-bin to world
```

**Comment by emmett1** [comment]
In your case, if on dependency number 10 is failed, installing process already stop, but all parents pkg already in world, even its not installed.

**Comment by XDream8** [comment]
You can test it yourself by cloning [my fork](https://github.com/XDream8/scratchpkg)
2022-08-11-192040_1338x490_scrot

**Comment by XDream8** [comment]
edit_world function makes sure to not add a port to world more than once. Also edit_world function checks if there is a error too

i know its in the loop but its after the pkgbuild -i so the port is installed. Then we check if port installed is the parent port(s) we wanted to install. 

even when installing a package with 30 dependencies if port we build in for loop and parent pkg names does not match it does not do anything to world

**Comment by emmett1** [comment]
you dont understand me. your fork does not work properly when installing multiple pkgs in one install command.

try this, make 3 dummy ports;
1st ports depends on a few ports.
2nd ports is broken, just add 'false' line in it.
3rd ports depends on a few ports.

Ok then, install those 3 dummy ports, 'scratch install port1 port2 port3'
it will failed on 2nd port (because of false cmd in it)

then check world files, i bet all 3 dummy ports in it even 3rd port not installed.

**Comment by emmett1** [comment]
i wait your test on this.

**Comment by emmett1** [comment]
this is my version https://github.com/venomlinux/scratchpkg/pull/29/files
you can test this too

**Comment by XDream8** [comment]
It works fine
2022-08-11-195136_1187x616_scrot

**Comment by XDream8** [comment]
Same result with yours
2022-08-11-200235_1336x636_scrot

**Comment by XDream8** [comment]
both mine and yours is fine, as long as they work as intended

**Comment by emmett1** [comment]
Alright.

**Pull request closed without merging**
